Cafe_MVC/Models/Contact.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace Cafe_MVC.Models
{
    public class Contact
    {
        [Required(ErrorMessage="این فیلد اجباری است ")]
        [MinLength(3,ErrorMessage ="حداقل طول نام 3 کاراکتر است ")]
        [MaxLength(100, ErrorMessage = "حداکثر طول نام 100 کاراکتر است ")]
        public string Name { get; set; }

        [Required(ErrorMessage = "این فیلد اجباری است ")]
        [EmailAddress(ErrorMessage ="ایمیل وارد شده صحیح نیست")]
        public string Email { get; set; }
        public string Message { get; set; }
        public int Service { get; set; }

        public SelectList Services { get; set; }
    }
}

Cafe_MVC/Models/ErrorViewModel.cs
namespace Cafe_MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Cafe_MVC/Models/IndexModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;

namespace Cafe_MVC.Models
{ 
    public class IndexModel
    {
        public List<Section2> Section2s { get;}
        public List<Section3> Section3s { get; }
        public List<Section4> Section4s { get; }
        public List<Section5> Section5s { get; }
    }
}

Cafe_MVC/Models/Section2.cs
using Microsoft.AspNetCore.Mvc;
namespace Cafe_MVC.Models
{
    public class Section2
    {
      
        public string Name { get; set; }
        public string Image { get; set; }



        //this is constructor (ctrl . keyboard)
        public Section2(string name, string image)
        {
            Name = name;
            Image = image;
        }
    }
}

Cafe_MVC/Models/Section3.cs
using Microsoft.AspNetCore.Mvc;

namespace Cafe_MVC.Models
{
    public class Section3
    {
        public string Name { get; set; }
        public string Image { get; set; }



        //this is constructor (ctrl . keyboard)
        public Section3(string name, string image)
        {
            Name = name;
            Image = image;
        }
    }
}

Cafe_MVC/Models/Section4.cs
namespace Cafe_MVC.Models
{
        public class Section4
        {
            public string Name { get; set; }
            public string Image { get; set; }



            //this is constructor (ctrl . keyboard)
            public Section4(string name, string image)
            {
                Name = name;
                Image = image;
            }
        }
   
}

Cafe_MVC/Models/Section5.cs
namespace Cafe_MVC.Models
{
    public class Section5
    {

        public string Name { get; set; }
        public string Image { get; set; }



        //this is constructor (ctrl . keyboard)
        public Section5(string name, string image)
        {
            Name = name;
            Image = image;
        }
    }
}

Cafe_MVC/Models/Service.cs
namespace Cafe_MVC.Models
{
    public class Service
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public Service (int id, string name)
        {
            Id = id;
            Name = name;
        }
    }
}

Cafe_MVC/Controllers/HomeController.cs
using Cafe_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;

namespace Cafe_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly List<Service> _services = new List<Service>
        {
                new Service(1 , "رزرو تولد"),
                new Service(2 , "خرید انلاین قهوه ارگانیک"),
                new Service(3 , "ثبت انتقادات و پیشنهادات"),
        };

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Contact()
        {
            var model = new Contact()
            {
                Services = new SelectList(_services,"Id" ,"Name")
            };
            return View(model);
        }


        //[HttpPost]
        // public JsonResult Contact(IFormCollection Form)
        //  {
        //      var name = Form["name"];
        //      return Json(Ok());
        //  }

        [HttpPost]
        public IActionResult Contact(Contact model)
        {
            model.Services= new SelectList(_services , "Id" ,"Name");
            if (!ModelState.IsValid)
            {
                ViewBag.error = "اطلاعات وارد شده صحیح نیست.لطفا دوباره تلاش کنید";
                return View(model);
            }

            ModelState.Clear();

            model = new Contact()
            {
                Services = new SelectList(_services, "Id", "Name")
            };

            ViewBag.success = "پیغام شما با موفقیت ارسال شد .با تشکر";
            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Cafe_MVC/ViewComponents/Section2ViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Cafe_MVC.Models;

namespace Cafe_MVC.ViewComponents
{
    public class Section2ViewComponent :ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var Section2s = new List<Section2>
           {
            new Section2("دمنوش","4859.jpg"),
             new Section2("هات چاکلت", "784.jpg"),
               new Section2("قهوه", "5446.jpg"),
                 new Section2("لاته", "11.jpg"),
                   new Section2("چای", "215.jpg"),
                     new Section2("نسکافه", "336655.jpg"),

           };
            return View("_Section2" ,Section2s);
        }

    }
}

Cafe_MVC/ViewComponents/Section3ViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Cafe_MVC.Models;

namespace Cafe_MVC.ViewComponents
{
    public class Section3ViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var Section3s = new List<Section3>
            {

          
             new Section3("موهیتو","5655.jpg"),
             new Section3("آب پرتقال","1515.jpg"),
             new Section3("آیس لاته","1588.jpg"),
             new Section3("اسموتی کیوی","8456.jpg"),
             new Section3("منگوبن","4895.jpg"),
           

            };

            //in return view ,we write the name of our viewcomponent
            return View("_Section3", Section3s);
        }
    }
}

Cafe_MVC/ViewComponents/Section4ViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Cafe_MVC.Models;

namespace Cafe_MVC.ViewComponents
{
    public class Section4ViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var Section4s = new List<Section4>
            {


                 new Section4("دارک بری","25.jpg"),
                 new Section4("کیک شکلاتی ","954.jpg"),
                 new Section4("کاپ کیک","6532.jpg"),
                 new Section4("کلاد کاکا","54216.jpg"),
                 new Section4("پنکیک کاراملی","65248.jpg"),
                 new Section4("موکا میوه ای","12.jpg"),




            };

            //in return view ,we write the name of our viewcomponent
            return View("_Section4", Section4s);
        }
    }
}

Cafe_MVC/ViewComponents/Section5ViewComponent.cs
using Cafe_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace Cafe_MVC.ViewComponents
{
    public class Section5ViewComponent:ViewComponent
    {

        public IViewComponentResult Invoke()
        {
            var Section5s = new List<Section5>
            {


                new Section5("شیک ردفروت","16.jpg"),
                new Section5("شیک شکلاتی","284.jpg"),
                new Section5("شیک بری","1511.jpg"),
                new Section5("شیک دارک","9543.jpg"),
                new Section5("شیک نوتلا","482.jpg"),
                new Section5("شیک نسکافه","8845.jpg"),










            };

            //in return view ,we write the name of our viewcomponent
            return View("_Section5", Section5s);
        }
    }
}

Cafe_MVC/Views/Home/Components/Section2/_Section2.cshtml
@model IEnumerable<Cafe_MVC.Models.Section2>


<div class="h1 text-center mt-5 " id="warmdrink" >نوشیدنی گرم</div>
<section class="section_2 ">
    <div class="swiper mySwiper container ">
        <div class="swiper-wrapper content ">

            @foreach(var Section2 in Model)
            {
                <div class="swiper-slide card " style="width: 18rem;">
                    <img class=" card-img-top rounded" src="~/assets/caffee/@Section2.Image" alt="@Section2.Name">
                    <h5 class="card-title text-center mt-3 text-light"> @Section2.Name  </h5>
                </div>
            }
          




        </div>

        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    </div>
</section>

Cafe_MVC/Views/Home/Components/Section3/_Section3.cshtml
@model List<Section3>

<div class="h1  text-center  mt-5" id="colddrink">نوشیدنی سرد</div>
<section class="section_3 ">
    <div class="swiper mySwiper container ">
        <div class="swiper-wrapper content   ">


            @foreach(var Section3 in Model)
            {
                  <div class="swiper-slide card " style="width: 18rem;">
                <img class=" card-img-top rounded" src="~/assets/caffee/@Section3.Image" alt="@Section3.Name">
                <h5 class="card-title text-center mt-3 text-light"> @Section3.Name</h5>
            </div>


            }
          

        </div>

        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    </div>
</section>

Cafe_MVC/Views/Home/Components/Section4/_Section4.cshtml
@model List<Section4>


<div class="h1  text-center mt-5" id="cakes">کیک</div>
<section class="section_4 ">
    <div class="swiper mySwiper container ">
        <div class="swiper-wrapper content   ">


            @foreach (var Section4 in Model)
            {
                <div class="swiper-slide card " style="width: 18rem;">
                    <img class=" card-img-top rounded" src="~/assets/caffee/@Section4.Image" alt="@Section4.Name">
                    <h5 class="card-title text-center mt-3 text-light"> @Section4.Name</h5>
                </div>


            }

       
        </div>

        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    </div>
</section>

Cafe_MVC/Views/Home/Components/Section5/_Section5.cshtml
@model List<Section5>


<div class="h1  text-center mt-5" id="milkshake">میلک شیک </div>
<section class="section_5 ">
    <div class="swiper mySwiper container ">
        <div class="swiper-wrapper content ">


            @foreach (var Section5 in Model)
            {
                <div class="swiper-slide card " style="width: 18rem;">
                    <img class=" card-img-top rounded" src="~/assets/caffee/@Section5.Image" alt="@Section5.Name">
                    <h5 class="card-title text-center mt-3 text-light"> @Section5.Name</h5>
                </div>


            }

        </div>

        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    </div>
</section>

Cafe_MVC/Views/Home/Contact.cshtml
@model Contact

@{
    ViewData["Title"] = "ارتباط با ما";
}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="assets/plugins/bootstrap-v4-rtl-master/bootstrap-rtl.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="~/assets/Style/CssStyle.css">
</head>
<body>

    <div class="main-wrapper">
        <section class="cta-section  py-5">
            <div class="container text-center single-col-max-width">
                <h2 class="heading text-light mb-5">ارتباط با ما</h2>
                <div class="intro text-light">
                    <p>
                        شما می توانید از طریق فرم زیر با ما ارتباط بگیرید. لطفا پس از پرکردن آیتم ها، پیغام مورد نظر را
                        نوشته و ارسال کنید.
                    </p>
                    <p>از طریق شبکه های اجتماعی با ما در ارتباط باشید</p>
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item mb-3">
                            <a class="twitter" href="#">
                                <i class="fab fa-twitter fa-fw fa-lg"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="instagram" href="#">
                                <i class="fab fa-instagram fa-fw fa-lg"></i>
                            </a>
                        </li>

                    </ul>
                </div>
             </div>
        </section>
    </div>
        <section class="contact-section px-3 py-5 p-md-5">
            <div class="container">

            @if (!string.IsNullOrWhiteSpace(ViewBag.success))
            {
                <div class="alert-success p-5">
                    <p> @ViewBag.success</p>
                </div>
            }

            @if (!string.IsNullOrWhiteSpace(ViewBag.error))
            {
                <div class="alert-danger p-5">
                    <p> @ViewBag.error</p>
                </div>
            }
         
                <form id="contact-form" class="contact-form col-lg-8 mx-lg-auto" method="post" asp-action="Contact">
                    <h3 class="text-center mb-3">در دسترس باشید!</h3>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label class="sr-only" asp-for="Name">نام</label>
                            <input type="text" class="form-control" asp-for="Name" placeholder="نام" >
                              <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label class="sr-only" asp-for="Email">ایمیل</label>
                            <input type="email" class="form-control" asp-for="Email" placeholder="ایمیل">
                           <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="form-group col-12">
                            <select class="custom-select" asp-for="Service" asp-items="Model.Services">
                                <option selected value="0"> نوع درخواست را انتخاب کنید...</option>
                            </select>
                        </div>
                        <div class="form-group col-12">
                            <label class="sr-only" asp-for="Message">پیغام شما</label>
                            <textarea class="form-control" asp-for="Message">
                                      placeholder="پیغام خود را وارد نمایید ..." rows="10"></textarea>
                        </div>
                        <div class="form-group col-12">
                            <button type="submit" class="btn btn-block btn-primary py-2">ارسال</button>
                        </div>
                    </div>
                </form>
            </div>
        </section>


        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

Cafe_MVC/Views/Home/Index.cshtml
@model IndexModel

@{
    ViewData["Title"] = "صفحه اصلی";
}


    <section class="section_header p-4">
        <div class="container text-center p-4 text-light " id="home">
            <div class="row">
                <div class="col-md-7 col-sm-12 ">

                    <h6>به کافه رزتا خوش آمدید </h6>
                    <h1> از طعمی که متفاوت است لذت ببرید </h1>

                    <button class="btn btn-dark mb-4 px-5 py-2 ">جهت رزرو </button>
                </div>

                <div class="col-md-5 col-sm-12 ">
                    <img src="./assets/caffee/2.png" alt="">

                </div>

            </div>
        </div>
    </section>

    <section class="section_1 p-5">
        <div class="container text-center">
            <div class="row">
                <div class=" col-md-6 col-sm-12 col-lg-6">
                    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img class="d-block w-100" src="./assets/caffee/27.jpg" alt="First slide">
                            </div>
                            <div class="carousel-item">
                                <img class="d-block w-100" src="./assets/caffee/19.jpg" alt="Second slide">
                            </div>
                            <div class="carousel-item">
                                <img class="d-block w-100" src="./assets/caffee/5464.jpg" alt="Third slide">
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
                <div class=" col-md-6 col-sm-12" id="aboutus">
                    <div class="panel ">
                        <h1>درباه ما</h1>
                        <p class="pt-4">
                            کافه رزتا در سال 1396 تاسیس شده و تا این لحظه مشغول خدمت به مشتریان عزیز خود بوده است .
                        </p>
                        <p> این کافه با اشتیاق اعلام می کند ارائه خدمات انلاین به مشتریان خود را نیز شروع کرده و زین پس مشتریان می توانند محصولات قهوه ارگانیک را  به صورت سفارشی و درب منزل دریافت کنند</p>
                    </div>
                </div>
            </div>
        </div>
    </section>




    <div class="container" id="menue">
        <div class="row  col-12 col-sm-12 col-md-12 col-lg-12 text-center justify-content-center ">
            <div class="swiper swiperbtn container">
                <div class="swiper-wrapper content">

                    <a href="#" class="btn swiper-slide rounded-pill text-light mr-1  btn-lg btn-primary  bg-dark  active" role="button" aria-pressed="true"> پیشنهاد ما</a>
                    <a href="#" class="btn swiper-slide rounded-pill text-light mr-1  btn-lg  btn-secondary bg-dark " role="button" aria-pressed="false">نوشیدنی سرد</a>
                    <a href="#" class="btn swiper-slide rounded-pill text-light mr-1  btn-lg  bg-dark" role="button" aria-pressed="false">نوشیدنی گرم</a>
                    <a href="#" class="btn swiper-slide rounded-pill text-light  mr-1 btn-lg  bg-dark" role="button" aria-pressed="false">کیک </a>
                    <a href="#" class="btn swiper-slide  rounded-pill text-light mr-1 btn-lg  bg-dark" role="button" aria-pressed="false">بستنی</a>
                    <a href="#" class="btn swiper-slide  rounded-pill text-light mr-1 btn-lg  bg-dark" role="button" aria-pressed="false">میلک شیک  </a>

                </div>
            </div>
        </div>
    </div>


    <div class="h1  text-center mt-5 pt-4" id="offer"> پیشنهاد ما</div>
    <section class="section_2">
        <div class="swiper mySwiper container ">
            <div class="swiper-wrapper content   ">
                <div class="swiper-slide card " style="width: 18rem;">
                    <img class=" card-img-top rounded" src="./assets/caffee/544.jpg" alt="Card image cap">
                    <h5 class="card-title text-center mt-3 text-light">Card title</h5>
                </div>

                <div class="swiper-slide card  " style="width: 18rem;">
                    <img class=" card-img-top rounded" src="./assets/caffee/16.jpg" alt="Card image cap">
                    <h5 class="card-title text-center mt-3 text-light">Card title</h5>
                </div>
                <div class="swiper-slide card " style="width: 18rem;">
                    <img class=" card-img-top rounded" src="./assets/caffee/284.jpg" alt="Card image cap">
                    <h5 class="card-title text-center mt-3 text-light">Card title</h5>
                </div>
                <div class="swiper-slide card " style="width: 18rem;">
                    <img class=" card-img-top rounded" src="./assets/caffee/482.jpg" alt="Card image cap">
                    <h5 class="card-title text-center mt-3 text-light">Card title</h5>
                </div>
                <div class="swiper-slide card  " style="width: 18rem;">
                    <img class=" card-img-top rounded" src="./assets/caffee/1511.jpg" alt="Card image cap">
                    <h5 class="card-title text-center mt-3 text-light">Card title</h5>
                </div>
                <div class="swiper-slide card " style="width: 18rem;">
                    <img class=" card-img-top rounded" src="./assets/caffee/942.jpg" alt="Card image cap">
                    <h5 class="card-title text-center mt-3 text-light">Card title</h5>
                </div>
            </div>

            <div class="swiper-button-next"></div>
            <div class="swiper-button-prev"></div>
        </div>
    </section>


 @*loading partial view*@
@*<partial name="Section2" />*@
@*@await Html.PartialAsync("Section2")*@
@*end loading partial view*@

@* loading view component *@
@await Component.InvokeAsync("Section2")

@await Component.InvokeAsync("Section3")

@await Component.InvokeAsync("Section4")

@await Component.InvokeAsync("Section5")
@* end view component *@

Cafe_MVC/Views/Shared/Footer.cshtml
<footer>
    <div class="container-fluid ">
        <div class="row ">

            <div class="col-md-4" id="contactus">
                <h4 class="text-light">ارتباط با ما</h4>
                <div class="column mt-3">
                    <i class="fab fa-facebook-f"></i>
                    <i class="fab fa-instagram "></i>
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-whatsapp"></i>
                </div>
            </div>

            <div class="col-md-4 text-light">
                <p class=" pt-2 ">

                    <h3>برو به </h3>
                    <br>
                    <a href="#home"> <i class="fas fa-arrow-right"></i> خانه </a><br>
                    <a href="#menue"> <i class="fas fa-arrow-right"></i> منیو</a><br>
                    <a href="#aboutus"> <i class="fas fa-arrow-right"></i> درباره ما</a><br>
                    <a href="#reservation"> <i class="fas fa-arrow-right"></i> رزرو </a>
                </p>
            </div>


            <div class="col-md-4 col-12 col-lg-4 col-sm-12">
                <p class="mt-5">
                    <span> copyright@2022 All rights reserved | This template is made by </span>
                    <span>Melika Solgi</span>
                </p>
            </div>

        </div>
    </div>
</footer>

Cafe_MVC/Views/Shared/Header.cshtml
<header>
    <div class="container-fluid ">
        <nav class="navbar navbar-expand-lg  ">
            <a class="navbar-brand " href="#">کافه رزتا</a>
            <button class="navbar-toggler navbar-dark  " type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon "></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarNav">
                <div class="mr-auto "></div>
                <ul class="navbar-nav  ">
                    <li class="nav-item active ">
                        <a class="nav-link p-0  " href="@Url.Action("Index", "Home")">خانه <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown  p-0 ">
                        <div class="dropdown ">
                            <a href="#menue" class="nav-link ">
                                منیو
                                <div class="dropdown-content ">
                                    <a href="#offer">پیشنهاد ما</a>
                                    <a href="#warmdrink">نوشیدنی گرم</a>
                                    <a href="#colddrink">نوشیدنی سرد</a>
                                    <a href="#cakes">کیک ها</a>
                                    <a href="#milkshake">میلک شیک </a>
                                </div>
                            </a>
                        </div>
                    </li>
                    <li class="nav-item p-0">
                        <a class="nav-link " href="#aboutus">درباره ما</a>
                    </li>
                    <li class="nav-item p-0">
                        <a class="nav-link " asp-controller="Home" asp-action="Contact">ارتباط با ما</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</header>

Cafe_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="eng">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Rozeta Cafe</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-v4-rtl-master/bootstrap-rtl.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <!-- Link Swiper's CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css" />

    <link rel="stylesheet" href="~/assets/Style/CssStyle.css">

</head>
<body>

    <partial name="Header" />

    <main>
        @RenderBody()
    </main>

    <partial name="Footer" />

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  
    @*validation jquery scripts*@
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <!-- Swiper JS -->
    <script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/Style/Js.js"></script>
</body>
</html>